# Use a base image with the necessary dependencies for testing
FROM python:3.8

# Set the working directory
WORKDIR /app

# Install testing dependencies
COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

# Copy the application code and tests
COPY svm_service /app/svm_service
COPY vgg19_service /app/vgg19_service
COPY front_service /app/front_service
COPY integration_tests /app/integration_tests

# Run the tests
CMD ["pytest", "/app/integration_tests"]