# Use a base image with the necessary dependencies for testing
FROM python:3.8

# Set the working directory
WORKDIR /app

# Install testing dependencies
COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

# Install any additional dependencies needed for testing
RUN pip install pytest

# Copy the application code and test configurations into the container
COPY . .

# Command to run the tests
# CMD ["pytest", "svm_service/tests/", "vgg19_service/tests/", "front_service/tests/"]

# # Run the tests
# CMD ["pytest", "/app/integration_tests"]